automation:
  - id: unifi_protect_person_detected_gazebo
    alias: Send message when person detected Gazebo
    mode: single
    
    description: >
      record and send a video when person seen
      
    trigger:
      - platform: homeassistant
        id: 'start'
        event: start
      - platform: event
        id: 'reload'
        event_type: automation_reloaded        
      - platform: state
        id: 'person'
        entity_id: binary_sensor.motion_gazebo
        to: person
        attribute: event_object
        
    variables:
      pic_file: "{{ 'gazebo_' + now().strftime('%d%m%H%M') }}"
      pic_folder: "/config/www/cam_snaps/"      
      
    action:
      - choose:
          - conditions: 
              - condition: trigger
                id: 'person'
            sequence:
              - service: input_text.set_value
                target:
                  entity_id: input_text.camera_gazebo_object_detected
                data:
                  value: "{{ trigger.to_state.attributes.event_object }}"
              - service: camera.record
                target:
                  entity_id: camera.gazebo
                data:
                  duration: 10
                  filename: "{{ pic_folder + pic_file }}.mp4"   
              - service: telegram_bot.send_message
                data:
                  target: !secret telegram_chat_id_bruce_and_sarah    
                  message_tag: object_detected_gazebo   
                  message: >
                    I have seen a {{ trigger.to_state.attributes.event_object }} on the Gazebo camera.
                    
                    Recording 10 seconds..........
              - wait_template: >
                  {{ pic_file in states.sensor.cam_snaps.attributes.file_list }}
                timeout: '00:00:20'
              - service: telegram_bot.edit_message
                data:
                  message_id: "{{ states('input_text.object_detected_gazebo_message_id') }}"
                  chat_id: !secret telegram_chat_id_bruce_and_sarah   
                  message: "I have seen a {{ trigger.to_state.attributes.event_object }} on the Gazebo camera."    
                  inline_keyboard:
                    - 'Show Video:/vdd_{{pic_file}}, OK:/remove_keyboard'      
              - delay: 00:05:00   
              
      - service: input_text.set_value
        target:
          entity_id: input_text.camera_gazebo_object_detected
        data:
          value: ""      
          
