sensor:
  - platform: mqtt
    name: "MQTT Export Power"
    device_class: power
    unit_of_measurement: "kW"
    icon: mdi:flash
    state_topic: !secret smart_hild_state_topic
    value_template: "{{ (value_json['elecMtr']['0702']['04']['00']|int(base=16) - 2**32) if (value_json['elecMtr']['0702']['04']['00']|int(base=16)  > (2**31) -1) else 0.0 }}"


  - platform: template
    sensors:
      export_power_integration:
        unique_id: export_power_integration
        friendly_name: Export Power
        unit_of_measurement: "kW"
        value_template: "{{((states('sensor.electricity_consumption') | float) / -1000.0) | round(2) if (states('sensor.electricity_consumption') | float ) < 20.0 else 0.0 }}"

