sensor:
  - platform: mqtt
    name: "Import Meter"
    state_topic: !secret smart_hild_state_topic
    unit_of_measurement: 'kWh'
    icon: mdi:speedometer
    value_template: "{{ (value_json['elecMtr']['0702']['00']['00']|int(base=16) * value_json['elecMtr']['0702']['03']['01']|int(base=16) / value_json['elecMtr']['0702']['03']['02']|int(base=16)) | int }}"