sensor:
  - platform: mqtt
    name: "Gas Meter kWh"
    icon: mdi:speedometer-slow
    state_topic: !secret smart_hild_state_topic
    unit_of_measurement: 'kWh'
    device_class: energy
    value_template: "{{ ( value_json['gasMtr']['0702']['00']['00']|int(base=16) * value_json['gasMtr']['0702']['03']['01']|int(base=16) / value_json['gasMtr']['0702']['03']['02']|int(base=16)) * 1.02264 * 39.1 / 3.6  }}"