automation:
  - id: dimmer_control_utility_lights
    alias: 'Dimmer Control of Utility Lights'
    mode: restart
    
    description: >
      Control utility light from dimmer switch
      
    trigger:
    - platform: event
      event_type: hue_event
      event_data:
        id: "utility_switch"
    - platform: state
      entity_id: light.utility_light
      to: 'off'      
      
    action:
      - choose:
          - conditions: "{{ trigger.entity_id == 'light.utility_light' }}"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.utility_light_manually_on      
          - conditions: "{{ trigger.event.data.event == 1002 }}"   
            sequence:          
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.utility_light_manually_on
          - conditions: "{{ trigger.event.data.event == 4000 }}"   
            sequence:          
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.utility_light_manually_on



