sensor:
  - platform: template
    sensors:
      washing_machine_state:
        unique_id: washing_machine_state
        friendly_name: "Washing Machine State"
        value_template: >
          {% if (states('sensor.washing_machine_power') | float) > 700.00 %}Heating{% 
          elif (states('sensor.washing_machine_power') | float) > 190.00 %}Fast-Spin{% 
          elif (states('sensor.washing_machine_power') | float) > 90.00 %}Spin{% 
          elif (states('sensor.washing_machine_power') | float) > 50.00 %}Washing{% 
          elif (states('sensor.washing_machine_power') | float) > 5.00 %}Standby{%           
          elif (states('sensor.washing_machine_power') | float) > 1.00 %}Standby{% 
          elif (states('sensor.washing_machine_power') | float) > 0.00 %}Soft-Off{% 
          else %}Off{% endif %}
        