automation:
  - id: garden_colour_lights_on_when_dark
    alias: 'Garden Colour Lights on when dark'
    mode: restart
    
    description: >-
      Lights on at dusk

    trigger: 
      - platform: state
        entity_id: 
          - binary_sensor.light_outside
          - alarm_control_panel.texecom
          - switch.sarah_is_asleep
          - switch.bruce_is_asleep
      - platform: homeassistant
        id: "start"
        event: start
      - platform: event
        id: "reload"
        event_type: automation_reloaded    

    action:
      - choose:
          - conditions: 
              - condition: state
                entity_id: binary_sensor.light_outside
                state: 'off'
              - condition: state
                entity_id: switch.sarah_is_asleep
                state: 'off'
              - condition: state
                entity_id: switch.bruce_is_asleep
                state: 'off'
              - condition: state
                entity_id: alarm_control_panel.texecom
                state: 'disarmed'                
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.garden_colour

        default:
          - service: light.turn_off
            target:
              entity_id: light.garden_colour        