automation:
  - id: dimmer_control_patio_lights
    alias: 'Dimmer Control of Patio Lights'
    mode: restart

    description: >-
      patio lights on and off with dimmer control

    trigger:
      - platform: event
        event_type: hue_event
        event_data:
          id: "patio_switch"
      - platform: state
        entity_id: light.patio_lights
        to: 'off'    

    action:
      - choose:
          - conditions: "{{ trigger.entity_id == 'light.patio_lights' }}"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.patio_lights_manually_on       

          - conditions: "{{ trigger.event.data.event == 1002 }}"   
            sequence:          
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.patio_lights_manually_on
                  
          - conditions: "{{ trigger.event.data.event == 4000 }}"   
            sequence:          
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.patio_light_manually_on
