#template:
#  - sensor:
#      - name: ForecastSolar Power Now
#        state: "{{ ((states('sensor.power_production_now_sw')|float + states('sensor.power_production_now_se')|float + states('sensor.power_production_now_nw')|float + states('sensor.power_production_now_ne')|float)/1000.0) | round(1) }}"
#        unit_of_measurement: "kW"
#        unique_id: forecastsolar_power_now
        

sensor:
  - platform: template
    sensors:
      forecastsolar_power_now:
        friendly_name: ForecastSolar Power Now
        value_template: "{{ ((states('sensor.power_production_now_sw')|float + states('sensor.power_production_now_se')|float + states('sensor.power_production_now_nw')|float + states('sensor.power_production_now_ne')|float)/1000.0) | round(1) }}"
        unit_of_measurement: "kW"
        device_class: Power
        
