automation:
  # Smoke trigger - Critical Notication
  - id: smoke_alarm_triggered
    alias: Smoke Alarm
    description: Smoke alarm
    trigger:
      - entity_id: 
          - binary_sensor.protect_garage_smoke
          - binary_sensor.protect_kate_smoke
          - binary_sensor.protect_stairs_smoke     
          - binary_sensor.protect_downstairs_smoke          
          - binary_sensor.protect_loft_smoke            
        platform: state
        to: "on"
    action:
    - service: notify.bruce_and_sarah_phones
      data:
        title: Smoke Alarm Triggered"
        message: The smoke alarm is going off!
        data:
          push:
            sound:
              name: default
              critical: 1
              volume: 1.0
    - service: persistent_notification.create
      data:
        title: "Smoke Alarm Triggered"
        message: "The smoke alarm is going off!"
        notification_id: Smoke