automation:
  - id: sky_and_amp_onoff_with_tv
    alias: 'Sky and Amp on Off with TV'
    mode: restart
  
    description: >
      Sky and Amp on and off with TV
    
    trigger:
      - platform: state
        id: 'on'
        entity_id: media_player.lounge_tv
        to: 'on'
      - platform: state
        id: 'off'
        entity_id: media_player.lounge_tv
        to: 'off'  
      - platform: state
        id: 'playing'
        entity_id: media_player.lounge_android
        to: 'and_playing'
      - platform: state
        id: 'and_off'
        entity_id: media_player.lounge_android
        to: 
          - 'off'          
          - 'standby'
      
    action:
      - choose:
          - conditions: 
              - condition: trigger
                id: 'on'
              - condition: trigger
                id: 'playing'                
            sequence:
              - condition: state
                entity_id: media_player.lounge_amp
                state: 'off'
              - service: script.skytv_turn_on
          - conditions: 
              - condition: trigger
                id: 'off' 
              - condition: trigger
                id: 'and_off'                      
            sequence:
              - condition: state
                entity_id: media_player.lounge_amp
                state: 'on'            
              - service: script.skytv_turn_off              