automation:
  - id: lounge_lights_when_door_opened
    alias: 'Lounge Lights on from door'
    mode: restart
    
    description: >
      Lounge Lights on when door opened

    trigger:
      - platform: state
        id: "door"
        entity_id: binary_sensor.lounge_door
        from: 'off'
        to: 'on'
        
    condition:
      - condition: state
        entity_id: binary_sensor.dark_outside
        state: 'on'
      - condition: state
        entity_id: light.lounge_lights
        state: 'off'
        
    action:
      - service: light.turn_on
        target:
          entity_id: 
            - light.lounge_lamp
            - light.lounge_left_back
            - light.lounge_left_front            
            - light.lounge_right            
        data:
          brightness: 75
