automation:
  - id: under_stairs_light_from_door
    alias: Under stairs lights on and off from door
    mode: restart
    
    description: >
      Understairs light on and off with door and timer
    
    trigger: 
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded    
      - platform: state
        entity_id: binary_sensor.under_stairs_door
        to: 
          - 'on'
          - 'off'
          
    action:
      - service: light.turn_{{ states('binary_sensor.under_stairs_door') }}
        target:
          entity_id: light.under_stairs_light          
      - delay: 00:15:00
      - service: light.turn_off
        target:
          entity_id: light.under_stairs_light            