automation:
  - id: link_zappi_charge_mode
    alias: 'Link Charge Mode Drop Down'
    mode: queued
    
    description: >
      Zappi Charge Mode Drop Down Sync with Zappi Mode
      
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded      
      - platform: state
        entity_id: 
          - input_select.zappi_jyggy_charge_mode
          - sensor.zappi_jyggy_mode
          - input_select.zappi_paddy_charge_mode
          - sensor.zappi_paddy_mode
          
    condition: "{{ states('sensor.zappi_jyggy_mode') != Unavailable }}"
    
    action:
      - choose:
            # Home Assistant Re-start of Automation Re-load
          - conditions: "{{ trigger.platform in ('homeassistant','event') }}"
            sequence:
              - alias: "Wait until previous Zappi Jyggy command is complete"
                wait_template: "{{ states('sensor.zappi_jyggy_cmt') | int > 250 }}"               
              - alias: "Set input select to Zappi Jyggy Charge Mode"
                service: input_select.select_option
                target: 
                  entity_id: input_select.zappi_jyggy_charge_mode
                data:
                  option: "{{ states('sensor.zappi_jyggy_mode') }}"
              - alias: "Wait until previous Zappi Paddy command is complete"
                wait_template: "{{ states('sensor.zappi_paddy_cmt') | int > 250 }}"               
              - alias: "Set input select to Zappi Paddy Charge Mode"
                service: input_select.select_option
                target: 
                  entity_id: input_select.zappi_paddy_charge_mode
                data:
                  option: "{{ states('sensor.zappi_paddy_mode') }}"                  

            # Requested Zappi Jyggy Mode has changed       
          - conditions: "{{ trigger.entity_id == 'input_select.zappi_jyggy_charge_mode' }}"
            sequence:
              - alias: "Wait until previous Zappi Jyggy command is complete"
                wait_template: "{{ states('sensor.zappi_jyggy_cmt') | int > 250 }}"    
              - condition: template
                value_template: "{{ states('input_select.zappi_jyggy_charge_mode') != states('sensor.zappi_jyggy_mode') }}"                
              - alias: "Send charge mode command to Zappi Jyggy"
                service: script.zappi_mode
                data:
                  mode: "{{ states('input_select.zappi_jyggy_charge_mode') }}"
                  serial: !secret zappi_serial_jyggy
                  name: "jyggy"
              - delay: 2
              - service: homeassistant.update_entity
                target:
                  entity_id: sensor.zappi_jyggy
                  
            # Requested Zappi Paddy Mode has changed 
          - conditions: "{{ trigger.entity_id == 'input_select.zappi_paddy_charge_mode' }}"
            sequence:
              - alias: "Wait until previous command is complete"
                wait_template: "{{ states('sensor.zappi_paddy_cmt') | int > 250 }}"    
              - condition: template
                value_template: "{{ states('input_select.zappi_paddy_charge_mode') != states('sensor.zappi_paddy_mode') }}"         
              - alias: "Send charge mode command to Zappi Paddy"                
                service: script.zappi_mode
                data:
                  mode: "{{ states('input_select.zappi_paddy_charge_mode') }}"   
                  serial: !secret zappi_serial_paddy
                  name: "paddy"                  
              - delay: 2
              - service: homeassistant.update_entity
                target:
                  entity_id: sensor.zappi_paddy

            # Zappi Mode has changed and current command has completed
          - conditions: "{{ trigger.entity_id == 'sensor.zappi_jyggy_mode' }}"
            sequence:
              - alias: "Wait until Zappi Jyggy command is complete"
                wait_template: "{{ states('sensor.zappi_jyggy_cmt') | int > 250 }}"      
              - alias: "Set Drop Down to charge mode for Zappi Jyggy"  
                service: input_select.select_option
                target: 
                  entity_id: input_select.zappi_jyggy_charge_mode
                data:
                  option: "{{ states('sensor.zappi_jyggy_mode') }}"

            # Zappi Mode has changed and current command has completed
          - conditions: "{{ trigger.entity_id == 'sensor.zappi_paddy_mode' }}"
            sequence:
              - alias: "Wait until Zappi Paddy command is complete"
                wait_template: "{{ states('sensor.zappi_paddy_cmt') | int > 250 }}"    
              - alias: "Set Drop Down to charge mode for Zappi Paddy"             
                service: input_select.select_option
                target: 
                  entity_id: input_select.zappi_paddy_charge_mode
                data:
                  option: "{{ states('sensor.zappi_paddy_mode') }}"
