automation:
  - id: eddi_off_at_agile_peak
    alias: 'Hot Water: Turn off for Peak'

    description: >
      Eddi off at Peak
    
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded      
      - platform: state
        entity_id: binary_sensor.agile_peak
  
        
    action:
      - delay: 00:00:05
      - service: script.eddi_on_or_off
        data:
          mode: "{{ is_state('binary_sensor.agile_peak','off') }}"

