automation:
  - id: eddi_boost_when_below_Xp
    alias: 'Hot Water: Turn on when below Xp'
    
    description: >
      When Price is below Xp boost eddi
      
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded       
      - platform: state
        entity_id: 
          - octopusagile.rates
          - input_number.eddi_heat_below_x_pence
        
    condition:
      - condition: numeric_state
        entity_id: sensor.octopus_agile_current_rate
        below: input_number.eddi_heat_below_x_pence
        
    action:
      - service: script.eddi_boost
        data:
          mode: "on"
          duration: 30
          heater: 1
      - alias: "Wait for myEnergi Update"
        wait_for_trigger:
          - platform: state
            entity_id: sensor.eddi_cmt
      - alias: "Wait until command is complete"
        wait_template: "{{ states('sensor.eddi_cmt') | int > 250 }}" 
#      - delay: 3
#      - condition: template      
#        value_template: "{{ (states('input_select.zappi_jyggy_charge_mode') != states('sensor.zappi_jyggy_mode')) }}"
#      - service: telegram_bot.send_message
#        data:
#          target: !secret telegram_chat_id_bruce         
#          message: >
#            Zappi {{name}} failed to change to {{mode}}
#                
#            {% if name == 'jyggy' %}Currently set to {{ states('sensor.zappi_jyggy_mode') }}
#            
#            Last Online at: {{ state_attr('sensor.zappi_jyggy','dat') + ' ' + state_attr('sensor.zappi_jyggy','tim') }}     
#
#            {% else %}Currently set to {{ states('sensor.zappi_paddy_mode') }}
#            
#            Last Online at: {{ state_attr('sensor.zappi_paddy','dat') + ' ' + state_attr('sensor.zappi_paddy','tim') }}    
#            {% endif %} 
 