automation:
  - id: check_plate_when_vehicle_detected
    alias: 'Check Plate when vehicle recognised'
    mode: single

    description: >-
      If vehicle detected on drive.
      Trigger several plate recogniser triggers
      
    trigger: 
      - platform: state
        id: "vehicle"
        entity_id:  binary_sensor.motion_drive
        to: vehicle
        attribute: event_object    

    action:
      - alias: 'Call plate Recogniser twice'
        repeat:
          count: 2
          sequence:
            - service: image_processing.scan
              target:
                entity_id: image_processing.platerecognizer_drive
            - delay: 2

