automation:
  - id: all_away_is_everything_off
    alias: 'Check everything off when noone at home'
    
    description: >
      Check everything off when noone at home

    trigger:
      - platform: state
        id: "not home"
        entity_id: group.someone_home
        from: home
        to: not_home
        
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.texecom
          state: disarmed
        - condition: state
          entity_id: 
            - fan.bedroom_fan
            - fan.conservatory_fan
            - light.home
            - input_boolean.watching_skytv 
        # Doors open that should be closed
            - binary_sensor.conservatory_door 
            - binary_sensor.front_door
            - binary_sensor.back_gate_door
            - binary_sensor.back_door
            - binary_sensor.under_stairs_door
            - binary_sensor.kates_bedroom_door
            - binary_sensor.sophies_bedroom_door
            - binary_sensor.master_bedroom_door
            - binary_sensor.bar_door
            - binary_sensor.lounge_door
          state: 'on'
        - condition: state
          entity_id: 
            - media_player.kitchen_sonos
            - media_player.sophies_sonos
            - media_player.kates_sonos
            - media_player.master_bed_sonos
            - media_player.bar_sonos
            - media_player.lounge_sonos
          state: playing
        # Doors closed that should be open
        - condition: state
          entity_id: 
            - binary_sensor.main_bathroom_door
            - binary_sensor.downstairs_toilet_door
          state: 'off'
          
    action:
      - service: telegram_bot.send_message
        data:
          target: !secret telegram_chat_id_bruce_and_sarah
          message_tag: all_away
          title: "Everyone is Out"
          message: >
            {% if is_state('alarm_control_panel.texecom','disarmed') %}Alarm is not set
            
            {% endif %}{% if is_state('fan.bedroom_fan','on') %}Bedroom Fan is on
            
            {% endif %}{% if is_state('fan.conservatory_fan','on') %}Conservatory Fan is on
            
            {% endif %}{% if is_state('light.downstairs','on') %}Lights are on downstairs
            
            {% endif %}{% if is_state('light.outside','on') %}Lights are on Outside
            
            {% endif %}{% if is_state('light.upstairs','on') %}Lights are on upstairs
            
            {% endif %}{% if is_state('input_boolean.watching_skytv','on') %}TV on in lounge
            
            {% endif %}{% if is_state('media_player.kitchen_sonos','playing') %}SONOS playing in the kitchen
            
            {% endif %}{% if is_state('media_player.sophies_sonos','playing') %}SONOS playing in Sophie bedroom
            
            {% endif %}{% if is_state('media_player.kates_sonos','playing') %}SONOS playing in Kate bedroom
            
            {% endif %}{% if is_state('media_player.lounge_sonos','playing') %}SONOS playing in the Lounge
            
            {% endif %}{% if is_state('media_player.bar_sonos','playing') %}SONOS playing in the Bar
            
            {% endif %}{% if is_state('binary_sensor.front_door','on') %}conservatory door is open
            
            {% endif %}{% if is_state('binary_sensor.front_door','on') %}front door is open
            
            {% endif %}{% if is_state('binary_sensor.back_gate_door','on') %}back gate is open
            
            {% endif %}{% if is_state('binary_sensor.back_door','on') %}back door is open
            
            {% endif %}{% if is_state('binary_sensor.under_stairs_door','on') %}under stairs door is open
            
            {% endif %}{% if is_state('binary_sensor.master_bedroom_door','on') %}master bedroom door is open
            
            {% endif %}{% if is_state('binary_sensor.lounge_door','on') %}lounge door is open
            
            {% endif %}{% if is_state('binary_sensor.bar_door','on') %}bar door is open
            
            {% endif %}{% if is_state('binary_sensor.sophies_bedroom_door','on') %}Sophie's door is open
            
            {% endif %}{% if is_state('binary_sensor.kates_bedroom_door','on') %}Kate's door is open
            
            {% endif %}{% if is_state('binary_sensor.guest_bedroom_door','on') %}Guest's door is open
            
            {% endif %}{% if is_state('binary_sensor.downstairs_toilet_door','off') %}Downstairs Loo door is closed
            
            {% endif %}{% if is_state('binary_sensor.main_bathroom_door','off') %}Bathroom door is closed
            
            {% endif %}
            
          inline_keyboard: >
            [{% if is_state('alarm_control_panel.texecom','disarmed') %}[['Arm Alarm', '/empty_house_arm_away']], {% endif 
            %}{% if is_state('fan.bedroom_fan','on') or is_state('fan.conservatory_fan','on') %}[['Fans Off', '/fans_off']], {% endif 
            %}{% if is_state('light.downstairs','on') or is_state('light.outside','on') or is_state('light.upstairs','on')  %}[['Lights Off', '/lights_off']], {% endif 
            %} [['OK', '/remove_keyboard']]]
