automation:
  - id: ios_action_hottub_jet1
    alias: "HotTub Jet 1 from ios"

    description: >
      Toggle HotTub Jet 1 from ios
      
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: 'HotTub Jet 1'
          
    action:
      - service: fan.toggle
        target:
          entity_id: fan.spa_pump1
