automation:
  - id: hottub_change_target
    alias: 'HotTub Change Target'
    mode: restart
    
    description: >
      Change target when input number updated
      
    trigger:
      - platform: state
        id: 'target changed'
        entity_id: input_number.hottub_water_target
      - platform: state
        id: 'back online'
        entity_id: binary_sensor.bwa_wi_fi_module
        to: 'on'
        
    action:
      - delay: 5    
      - service: climate.set_temperature
        target: 
          entity_id: climate.spa_climate
        data:
          temperature: "{{ states('input_number.hottub_water_target') | round(1, 'half') }}"

