automation:
  - id: boost_hot_water_when_cold
    alias: 'hot water boost if water cold'
    mode: single
    
    description: >
      Boost the water if it is cold
      
    trigger:
        # don't know why I have it run at 6am ?
      - platform: time
        at: '06:00:00'
      - platform: numeric_state
        entity_id: sensor.eddi_water_temp
        below: 45.0
        for:
          minutes: 1
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded       
        
    condition: 
      - condition: numeric_state
        entity_id: sensor.eddi_water_temp
        below: 47.0
        above: 10.0        
        
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.hive_water_boost