sensor:
  - platform: template
    sensors:
      solcast_forecast_tomorrow_rounded:
        unique_id: solcast_forecast_tomorrow_rounded
        friendly_name: "SolCast Tomorrow"
        unit_of_measurement: 'kWh'            
        device_class: power
        value_template: "{{ states('sensor.energy_production_forecast_tomorrow') | round(1) }}"    
