sensor:
  - platform: template
    sensors:
        solcast_forecast_the_day_after_tomorrow:
            friendly_name: "SolCast the Day After Tomorrow"
            unit_of_measurement: 'kWh'
            device_class: power            
            value_template: "{{ state_attr('sensor.solcast_forecast', 'the day after tomorrow')  }}"    
#            value_template: "{{ state_attr('sensor.solcast_forecast_a', 'the day after tomorrow') | float + state_attr('sensor.solcast_forecast_b', 'the day after tomorrow') | float}}"                
            